#Robocode Robot
#Tue May 26 00:27:24 GMT-03:00 2026
robocode.version=1.10.1
robot.author.name=Leo
robot.classname=Trojan
robot.codesize=8307
robot.description=Cavalo de Tróia da Silva
robot.include.source=true
robot.version=1
